from pathlib import Path
from typing import Any, Dict, Iterable, List

from ontobdc.cli.domain.port.context import CliContextPort
from ontobdc.shared.adapter.capability import TransformationCapability
from ontobdc.shared.adapter.filesystem import FilesystemAdapter
from ontobdc.shared.domain.model.capability import CapabilityMetadata
from ontobdc_view.surface.domain.machine.standard_surface_html.state import SurfaceGenerationProcessState

_LEGACY_FILE_VIEWER_NAME = "onto-file-viewer.html"
_MARKER_DIRECTORY_NAME = ".__ontobdc__"


class ViewArtifactsCleanedCapability(TransformationCapability):
    """Remove every HTML, JavaScript and CSS view artefact from a prior run.

    Runs before `SURFACE_INITIALIZED` so a failed or stale prior run can
    never be mistaken for a resumable current build, and so the container's
    own file inventory (read by `DATA_GATHERED`, which runs one state
    earlier) never has to reason about the tool's own leftover output.

    Like `IS_PUBLISHABLE`/`DATA_GATHERED`, this state has no HTML document to
    carry a state marker yet, so `check()` answers directly from the
    filesystem instead of through `SurfaceTransformationAdapter`: the state
    is satisfied exactly when none of the generated artefacts exist.
    """

    METADATA = CapabilityMetadata(
        id=(
            "org.ontobdc.view.plugin.capability.transformation.target."
            "view_artifacts_cleaned"
        ),
        version="1.0.0",
        name="View Artifacts Cleaned",
        description=(
            "Remove HTML, JavaScript and CSS artefacts generated by a "
            "previous ontobdc view run for this container."
        ),
        author=["http://kb.elias.eng.br/nid/elias.ttl#Elias"],
        tags=["view", "surface", "cleanup", "transformation"],
        supported_languages=["en", "pt-br"],
        log_message={
            "info": {
                "en": (
                    "Every HTML, JavaScript and CSS artefact generated by a "
                    "previous ontobdc view run was removed."
                ),
            },
            "debug_entry": {
                "en": (
                    "Removing every HTML, JavaScript and CSS artefact generated "
                    "by a previous ontobdc view run."
                ),
            },
        },
    )

    def label(self, lang: str = "en") -> str:
        return SurfaceGenerationProcessState.VIEW_ARTIFACTS_CLEANED.label(lang)

    def description(self, lang: str = "en") -> str:
        return SurfaceGenerationProcessState.VIEW_ARTIFACTS_CLEANED.description(lang)

    def check(self, context: CliContextPort) -> bool:
        try:
            container_path = self._container_path(context)
        except ValueError:
            return False
        return not any(
            path.is_file()
            for path in self._generated_artifact_paths(container_path)
        )

    def execute(self, context: CliContextPort) -> Dict[str, Any]:
        container_path = self._container_path(context)
        removed: List[str] = []
        for path in self._generated_artifact_paths(container_path):
            if path.is_file():
                FilesystemAdapter.remove_file(path)
                removed.append(str(path))

        return {
            "resulting_state": SurfaceGenerationProcessState.VIEW_ARTIFACTS_CLEANED,
            "container_path": str(container_path),
            "removed_paths": removed,
        }

    def is_satisfied(self, context: CliContextPort) -> bool:
        return self.check(context)

    @staticmethod
    def _container_path(context: CliContextPort) -> Path:
        container_path = str(
            context.get_parameter_value("container_path") or ""
        ).strip()
        if not container_path:
            raise ValueError("The container path was not resolved.")
        return Path(container_path).expanduser().resolve()

    @classmethod
    def _generated_artifact_paths(
        cls,
        container_path: Path,
    ) -> Iterable[Path]:
        """Every HTML, JavaScript and CSS path generated by the view pipeline.

        The legacy asset layout is restricted to directories ending in
        ``_view`` so unrelated assets under ``.__ontobdc__/asset`` remain
        untouched.
        """
        yield container_path / "index.html"
        marker_directory = container_path / _MARKER_DIRECTORY_NAME
        # Legacy standalone file-viewer locations, from before it moved to
        # `.__ontobdc__/view/onto-file-viewer.html` (root level first, then
        # the marker directory root) -- cleaned so an old leftover never
        # resurfaces as an ordinary container file.
        yield container_path / _LEGACY_FILE_VIEWER_NAME
        yield marker_directory / _LEGACY_FILE_VIEWER_NAME
        # The current file viewer, entity Pages and their colocated runtime
        # scripts and styles live here.
        view_directory = marker_directory / "view"
        if view_directory.is_dir():
            for extension in ("html", "js", "css"):
                yield from sorted(view_directory.rglob(f"*.{extension}"))

        # Runtime assets generated by the legacy Page layout lived under
        # `.__ontobdc__/asset/<entity>_view/`.
        asset_directory = marker_directory / "asset"
        if asset_directory.is_dir():
            for entity_asset_directory in sorted(
                path
                for path in asset_directory.glob("*_view")
                if path.is_dir()
            ):
                for extension in ("js", "css"):
                    yield from sorted(
                        entity_asset_directory.rglob(f"*.{extension}")
                    )
