from pathlib import Path

from infobim.view.domain.model import InfoBIMProjectPresentation
from infobim.view.plugin.command import project as command_module
from infobim.view.plugin.command.project import ViewProjectCommand
from ontobdc.cli.adapter.context import CliContextAdapter
from ontobdc.cli.domain.request.command import CliCommandRequest
from ontobdc.cli.domain.response.command import CommandResponse


def test_project_view_delegates_generation_to_specialized_ontobdc_handler(
    tmp_path: Path,
    monkeypatch,
) -> None:
    context = CliContextAdapter(
        ["view", "--project-id", "project-123"]
    )
    request = CliCommandRequest(
        logical_component="view",
        component_action="view_project",
        command_args=["--project-id", "project-123"],
        context=context,
    )
    command = ViewProjectCommand(request)

    def resolve_project(_self, target_context):
        target_context.set_parameter_value("project_id", "project-123")
        target_context.set_parameter_value("project_path", str(tmp_path))
        target_context.set_parameter_value("container_id", "container-123")
        target_context.set_parameter_value("container_path", str(tmp_path))
        return target_context

    presentation = InfoBIMProjectPresentation(
        project_id="project-123",
        project_path=str(tmp_path),
        project_subject="urn:test:project",
        project={"GlobalId": "project-123", "Name": "Project"},
        classes=(),
    )

    class FakeHandler:
        def __init__(self, *, context, presentation):
            assert presentation.project_id == "project-123"
            self.context = context

        def execute(self):
            (tmp_path / "index.html").write_text(
                "generated by generic Surface pipeline",
                encoding="utf-8",
            )
            return CommandResponse(
                title="Presentation Surface Generated",
                description="done",
                content={"visited_states": ["surface_validated"]},
            )

    monkeypatch.setattr(
        command_module.ProjectIdStrategy,
        "execute",
        resolve_project,
    )
    monkeypatch.setattr(
        command_module.InfoBIMProjectPresentationRepository,
        "load",
        lambda _self, **_kwargs: presentation,
    )
    monkeypatch.setattr(
        command_module.InfoBIMComponentSourceAdapter,
        "scripts",
        lambda _self, **_kwargs: ["generic-surface-component"],
    )
    monkeypatch.setattr(
        command_module,
        "InfoBIMSurfaceGenerationStateTransitionHandler",
        FakeHandler,
    )
    monkeypatch.setattr(command_module.webbrowser, "open", lambda *_a, **_k: True)
    monkeypatch.setattr(
        command_module.InfoBIMSurfaceRegenerationWorkerLauncher,
        "ensure_running",
        lambda _self, **_kwargs: 4321,
    )

    assert command.check()
    response = command.run()
    assert response.content["project_id"] == "project-123"
    assert response.content["container_id"] == "project-123"
    assert response.content["index_path"] == str(tmp_path / "index.html")
    assert response.content["browser_opened"] is True
    assert response.content["regeneration_worker_pid"] == 4321
    assert "<html" not in str(response.content).lower()


def test_project_view_rejects_two_project_selectors() -> None:
    assert not ViewProjectCommand.accepts(
        [
            "view",
            "--project-id",
            "project-123",
            "--project",
            "project-456",
        ]
    )
